### ISSUE TITLE
 pointerIndex out of range

### ISSUE THREAD

**Issue by Sereri** [OrangeGangsters/SwipyRefreshLayout#19]
Saw this exception in one of the crashreports of my app, thought it might interest you:

```
java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getY(MotionEvent.java:2029)
       at android.support.v4.view.MotionEventCompatEclair.getY(MotionEventCompatEclair.java:35)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getY(MotionEventCompat.java:114)
       at android.support.v4.view.MotionEventCompat.getY(MotionEventCompat.java:471)
       at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.onTouchEvent(SwipyRefreshLayout.java:914)
       at android.view.View.dispatchTouchEvent(View.java:8471)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2373)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2375)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2375)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2375)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.support.v4.widget.DrawerLayout.cancelChildViewTouch(DrawerLayout.java:1491)
       at android.support.v4.widget.DrawerLayout$ViewDragCallback.peekDrawer(DrawerLayout.java:1739)
       at android.support.v4.widget.DrawerLayout$ViewDragCallback.access$000(DrawerLayout.java:1624)
       at android.support.v4.widget.DrawerLayout$ViewDragCallback$1.run(DrawerLayout.java:1630)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by aarcoraci** [comment]
Same happened to me today

**Comment by oliveeyay** [comment]
I think it has been fixed in the latest version.
[#108817170] Fix IllegalArgumentException in SwipyRefreshLayout
You should use    compile 'com.github.orangegangsters:swipy:1.2.1@aar'
