### ISSUE TITLE
CalledFromWrongThreadException

### ISSUE THREAD

**Issue by caijiangyang** [OrangeGangsters/SwipyRefreshLayout#31]
log:
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6386)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:926)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4691)
at android.view.View.invalidateInternal(View.java:11837)
at android.view.View.invalidate(View.java:11801)
at android.view.View.invalidateParentIfNeeded(View.java:11990)
at android.view.View.clearAnimation(View.java:17908)
at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.startScaleDownAnimation(SwipyRefreshLayout.java:446)

**Comment by oliveeyay** [comment]
You can't manipulate views from another thread than the main thread.
That's a big Android design architecture, not the library problem.

Cheers,

Olivier
