### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by ola-skorp** [OrangeGangsters/SwipyRefreshLayout#60]
Поместила ListView в SwipyRefreshLayout. Исключение происходит на устройствах с android от 4.1 до 4.4 включительно.

java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
    at android.widget.ListView.setupChild(ListView.java:1826)
    at android.widget.ListView.makeAndAddView(ListView.java:1793)
    at android.widget.ListView.fillDown(ListView.java:691)
    at android.widget.ListView.fillFromTop(ListView.java:752)
    at android.widget.ListView.layoutChildren(ListView.java:1616)
    at android.widget.AbsListView.onLayout(AbsListView.java:2087)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.onLayout(SwipyRefreshLayout.java:583)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1092)
    at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:802)
    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:816)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14841)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1743)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
    at dalvik.system.NativeStart.main(Native Method)

compile 'com.github.orangegangsters:swipy:1.2.3@aar'

**Comment by oliveeyay** [comment]
I think it's a mistake in your code (casting LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams)

**Comment by fengzuowei123** [comment]
child.layout(childLeft, childTop, childLeft + childWidth, childTop + childHeight);
